# Dev PostgreSQL settings
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}

## Dev App settings
app.oauth2.redirect-uri=${DEV_FRONTEND_URL:http://localhost:4000}/auth/callback
app.cookie.secure=${DEV_COOKIE_SECURE:false}

## Dev OAUTH2
spring.security.oauth2.client.registration.naver.redirect-uri=${DEV_NAVER_OAUTH_REDIRECT_URI:http://localhost:8000/login/oauth2/code/naver}
spring.security.oauth2.client.registration.google.redirect-uri=${DEV_GOOGLE_OAUTH_REDIRECT_URI:http://localhost:8000/login/oauth2/code/google}
spring.security.oauth2.client.registration.kakao.redirect-uri=${DEV_KAKAO_OAUTH_REDIRECT_URI:http://localhost:8000/login/oauth2/code/kakao}

## Dev Logging Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

logging.level.org.mybatis=DEBUG
logging.level.com.web.SearchWeb=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
