# Dev PostgreSQL settings
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}

## Dev OAUTH2
spring.security.oauth2.client.registration.naver.redirect-uri=${CLOUD_NAVER_OAUTH_REDIRECT_URI}
spring.security.oauth2.client.registration.google.redirect-uri=${CLOUD_GOOGLE_OAUTH_REDIRECT_URI}
spring.security.oauth2.client.registration.kakao.redirect-uri=${CLOUD_KAKAO_OAUTH_REDIRECT_URI}

## openai settings
#ai.openai.api-key=${OPENAI_API_KEY}
#ai.openai.chat.options.model=${OPENAI_API_MODEL}
#ai.openai.chat.options.temperature=${OPENAI_API_tmp}