version: '3.8'

services:
  # (1) 백엔드 스프링 부트 앱
  backend:
    image: ${DOCKERHUB_USERNAME}/relink-backend:latest
    container_name: relink-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_FORWARD_HEADERS_STRATEGY=native
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${PROD_VM2_INTERNAL_IP}:7000/${PROD_POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${PROD_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
    env_file:
      - ./.env
    restart: always

  # (2) Nginx 웹 서버
  nginx:
    image: ${DOCKERHUB_USERNAME}/relink-frontend:latest
    container_name: relink-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: searchweb-network
